//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public decimal id { get; set; }
        public string componente { get; set; }
        public string parametros { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
