//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_TABLA_PASO_POLIZAS
    {
        public decimal tab_id { get; set; }
        public decimal pal_id_lote_pago { get; set; }
        public string pad_polTipo { get; set; }
        public decimal pad_polAnnio { get; set; }
        public decimal pad_polMes { get; set; }
        public decimal pad_polConsecutivo { get; set; }
        public decimal pad_polMovimiento { get; set; }
        public Nullable<System.DateTime> pad_fechaPromesaPago { get; set; }
        public Nullable<decimal> pad_saldo { get; set; }
        public string tab_revision { get; set; }
        public string pad_polReferencia { get; set; }
        public string pad_documento { get; set; }
        public Nullable<int> pad_agrupamiento { get; set; }
        public string pad_bancoPagador { get; set; }
        public string pad_bancoDestino { get; set; }
    }
}
