//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_SELECT_PRUEBA
    {
        public decimal pal_id_lote_pago { get; set; }
        public decimal pad_id { get; set; }
        public string pad_polTipo { get; set; }
        public decimal pad_polAnnio { get; set; }
        public decimal pad_polMes { get; set; }
        public decimal pad_polConsecutivo { get; set; }
        public decimal pad_polMovimiento { get; set; }
        public Nullable<System.DateTime> pad_polFechaOperacion { get; set; }
        public string pad_cuenta { get; set; }
        public Nullable<decimal> pad_idProveedor { get; set; }
        public string pad_proveedor { get; set; }
        public string pad_documento { get; set; }
        public string pad_tipo { get; set; }
        public string pad_tipoDocto { get; set; }
        public string pad_cartera { get; set; }
        public Nullable<decimal> pad_monto { get; set; }
        public Nullable<decimal> pad_saldo { get; set; }
        public Nullable<decimal> pad_saldoPorcentaje { get; set; }
        public string pad_moneda { get; set; }
        public Nullable<System.DateTime> pad_fechaVencimiento { get; set; }
        public Nullable<System.DateTime> pad_fechaPromesaPago { get; set; }
        public Nullable<System.DateTime> pad_fechaRecepcion { get; set; }
        public Nullable<System.DateTime> pad_fechaFactura { get; set; }
        public string pad_ordenCompra { get; set; }
        public string pad_idEstatus { get; set; }
        public string pad_estatus { get; set; }
        public Nullable<decimal> pad_anticipo { get; set; }
        public Nullable<decimal> pad_anticipoAplicado { get; set; }
        public Nullable<decimal> pad_annio { get; set; }
        public string pad_proveedorBloqueado { get; set; }
        public string pad_ordenBloqueada { get; set; }
        public Nullable<decimal> pad_diasCobro { get; set; }
        public string pad_aprobado { get; set; }
        public Nullable<decimal> pad_contReprog { get; set; }
        public string pad_documentoPagable { get; set; }
        public Nullable<int> pad_aPagar { get; set; }
        public string pad_nombreAgrupador { get; set; }
        public Nullable<decimal> pad_ordenAgrupador { get; set; }
        public Nullable<decimal> pad_ordenProveedor { get; set; }
    }
}
