//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_FLUJO_EFECTIVO_Borrar
    {
        public decimal pfe_id { get; set; }
        public Nullable<decimal> pfe_saldo_banco { get; set; }
        public Nullable<decimal> pfe_saldo_caja { get; set; }
        public Nullable<decimal> pfe_cobranza_esperada { get; set; }
        public Nullable<decimal> pfe_flujo_efectivo { get; set; }
        public Nullable<decimal> pfe_disponible { get; set; }
        public string pfe_var_aux1 { get; set; }
        public string pfe_var_aux2 { get; set; }
        public string pfe_var_aux3 { get; set; }
    }
}
