//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_CAT_AGRUPADORES
    {
        public decimal pca_idAgrupador { get; set; }
        public decimal pca_idEmpresa { get; set; }
        public string pca_nombre { get; set; }
        public string pca_descripcion { get; set; }
        public Nullable<int> pca_orden { get; set; }
        public string pca_estatus { get; set; }
        public string pca_ordenVarchar { get; set; }
    }
}
