//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_PROVEEDOR_CUENTA_Borrar
    {
        public decimal ppc_id { get; set; }
        public decimal ppc_idEmpresa { get; set; }
        public decimal ppc_idProveedor { get; set; }
        public string ppc_cuenta { get; set; }
    }
}
