//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_TRANSFERENCIAS_BANCARIAS
    {
        public decimal ptb_id { get; set; }
        public decimal pal_id_lote_pago { get; set; }
        public string ptb_id_cuenta_origen { get; set; }
        public string ptb_id_cuenta_destino { get; set; }
        public decimal ptb_importe { get; set; }
        public short ptb_estatus { get; set; }
    }
}
