//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_PROGRA_PAGOS
    {
        public decimal pag_id { get; set; }
        public decimal pag_idUsuario { get; set; }
        public System.DateTime pag_fecha { get; set; }
        public string pag_varAux1 { get; set; }
        public string pag_varAux2 { get; set; }
    }
}
