//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_REFERENCIA
    {
        public decimal pre_id_referencia { get; set; }
        public string pre_referencia { get; set; }
        public short pre_tipo { get; set; }
        public decimal pal_id_lote_pago { get; set; }
        public short pre_estatus { get; set; }
        public decimal pad_idProveedor { get; set; }
        public Nullable<int> pad_agrupamiento { get; set; }
    }
}
