//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_AGRUPADOR_PROVEEDOR
    {
        public decimal pca_idAgrupador { get; set; }
        public decimal pap_idProveedor { get; set; }
        public Nullable<int> pap_orden { get; set; }
    }
}
