//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_FLUJO_INGRESO_OTROS
    {
        public decimal pio_id { get; set; }
        public decimal pal_id_lote_pago { get; set; }
        public decimal pio_caja { get; set; }
        public decimal pio_cobranzaEsperada { get; set; }
    }
}
