//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_TABLA_PASO_POLIZAS_2
    {
        public int tab_id { get; set; }
        public decimal pag_id { get; set; }
        public string pad_polTipo { get; set; }
        public Nullable<decimal> pad_polAnnio { get; set; }
        public Nullable<decimal> pad_polMes { get; set; }
        public Nullable<decimal> pad_polConsecutivo { get; set; }
        public Nullable<decimal> pad_polMovimiento { get; set; }
        public Nullable<System.DateTime> pad_fechaPromesaPago { get; set; }
        public Nullable<decimal> pad_saldo { get; set; }
        public Nullable<int> pad_selecccionado { get; set; }
    }
}
