//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAG_CAT_PROVEEDORES
    {
        public int pcp_id { get; set; }
        public Nullable<decimal> pcp_idEmpresa { get; set; }
        public decimal pcp_idProveedor { get; set; }
        public string pcp_nombreProveedor { get; set; }
        public string pcp_bancoPagador { get; set; }
        public string pcp_cuentaPagadora { get; set; }
        public string pcp_claveCuentaPagadora { get; set; }
        public string pcp_bancoProveedor { get; set; }
        public string pcp_cuentaProveedor { get; set; }
        public string pcp_claveCuentaProveedor { get; set; }
        public string pcp_tipoProveedor { get; set; }
    }
}
