//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PagosEntities : DbContext
    {
        public PagosEntities()
            : base("name=PagosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PAG_CAT_AGRUPADORES> PAG_CAT_AGRUPADORES { get; set; }
        public virtual DbSet<PAG_COLUMNA> PAG_COLUMNA { get; set; }
        public virtual DbSet<PAG_ESCENARIOS_PAGOS> PAG_ESCENARIOS_PAGOS { get; set; }
        public virtual DbSet<PAG_ESTATUS_LOTE> PAG_ESTATUS_LOTE { get; set; }
        public virtual DbSet<PAG_ESTATUS_TRANSFERENCIAS> PAG_ESTATUS_TRANSFERENCIAS { get; set; }
        public virtual DbSet<PAG_LOTE_PAGO> PAG_LOTE_PAGO { get; set; }
        public virtual DbSet<PAG_PARAMETROS> PAG_PARAMETROS { get; set; }
        public virtual DbSet<PAG_PARAMETROS_EMPRESAS> PAG_PARAMETROS_EMPRESAS { get; set; }
        public virtual DbSet<PAG_REFERENCIA> PAG_REFERENCIA { get; set; }
        public virtual DbSet<PAG_TABLA_PASO_POLIZAS> PAG_TABLA_PASO_POLIZAS { get; set; }
        public virtual DbSet<PAG_TIPO_REFERENCIA_BANCOS> PAG_TIPO_REFERENCIA_BANCOS { get; set; }
        public virtual DbSet<PAG_TIPO_REFERENCIA_PLANTA> PAG_TIPO_REFERENCIA_PLANTA { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<PAG_AGRUPADOR_PROVEEDOR> PAG_AGRUPADOR_PROVEEDOR { get; set; }
        public virtual DbSet<PAG_CAT_PROVEEDORES> PAG_CAT_PROVEEDORES { get; set; }
        public virtual DbSet<PAG_COLUMNA_USUARIO> PAG_COLUMNA_USUARIO { get; set; }
        public virtual DbSet<PAG_FLUJO_EGRESO_BANCOS> PAG_FLUJO_EGRESO_BANCOS { get; set; }
        public virtual DbSet<PAG_FLUJO_INGRESO_BANCOS> PAG_FLUJO_INGRESO_BANCOS { get; set; }
        public virtual DbSet<PAG_FLUJO_INGRESO_OTROS> PAG_FLUJO_INGRESO_OTROS { get; set; }
        public virtual DbSet<PAG_PROGRA_PAGOS_BPRO> PAG_PROGRA_PAGOS_BPRO { get; set; }
        public virtual DbSet<PAG_PROGRA_PAGOS_DETALLE> PAG_PROGRA_PAGOS_DETALLE { get; set; }
        public virtual DbSet<PAG_PROVEEDOR_BANCO_PAGADOR> PAG_PROVEEDOR_BANCO_PAGADOR { get; set; }
        public virtual DbSet<PAG_REFERENCIA_DOCUMENTO> PAG_REFERENCIA_DOCUMENTO { get; set; }
        public virtual DbSet<PAG_TRANSFERENCIAS_BANCARIAS> PAG_TRANSFERENCIAS_BANCARIAS { get; set; }
    
        public virtual ObjectResult<string> APL_TRANSFERENCIASXEMPRESA(Nullable<int> idLote, Nullable<decimal> importe)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(int));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("importe", importe) :
                new ObjectParameter("importe", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("APL_TRANSFERENCIASXEMPRESA", idLoteParameter, importeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DEL_AGRUPADOR_PROVEEDOR_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DEL_AGRUPADOR_PROVEEDOR_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<string> DEL_LOTE_DETALLE_COMPLETO_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DEL_LOTE_DETALLE_COMPLETO_SP", idEmpresaParameter, idLoteParameter);
        }
    
        public virtual ObjectResult<DEL_LOTE_INCONCLUSO_SP_Result> DEL_LOTE_INCONCLUSO_SP(Nullable<decimal> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEL_LOTE_INCONCLUSO_SP_Result>("DEL_LOTE_INCONCLUSO_SP", idLoteParameter);
        }
    
        public virtual ObjectResult<DEL_LOTE_NO_APROBADO_SP_Result> DEL_LOTE_NO_APROBADO_SP(Nullable<decimal> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEL_LOTE_NO_APROBADO_SP_Result>("DEL_LOTE_NO_APROBADO_SP", idLoteParameter);
        }
    
        public virtual ObjectResult<string> DEL_PROVEEDOR_CUENTA_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idProveedor, string cuentaPagadora)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("IdProveedor", idProveedor) :
                new ObjectParameter("IdProveedor", typeof(decimal));
    
            var cuentaPagadoraParameter = cuentaPagadora != null ?
                new ObjectParameter("CuentaPagadora", cuentaPagadora) :
                new ObjectParameter("CuentaPagadora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DEL_PROVEEDOR_CUENTA_SP", idEmpresaParameter, idProveedorParameter, cuentaPagadoraParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_AGRUPADOR_PROVEEDOR_SP(Nullable<decimal> idAgrupador, Nullable<int> idProveedor, Nullable<int> ordenAgruProveedor)
        {
            var idAgrupadorParameter = idAgrupador.HasValue ?
                new ObjectParameter("idAgrupador", idAgrupador) :
                new ObjectParameter("idAgrupador", typeof(decimal));
    
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("idProveedor", idProveedor) :
                new ObjectParameter("idProveedor", typeof(int));
    
            var ordenAgruProveedorParameter = ordenAgruProveedor.HasValue ?
                new ObjectParameter("ordenAgruProveedor", ordenAgruProveedor) :
                new ObjectParameter("ordenAgruProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_AGRUPADOR_PROVEEDOR_SP", idAgrupadorParameter, idProveedorParameter, ordenAgruProveedorParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_APLICA_LOTE_SP(Nullable<int> emp_idempresa, Nullable<decimal> idLote, Nullable<decimal> idUsuario)
        {
            var emp_idempresaParameter = emp_idempresa.HasValue ?
                new ObjectParameter("emp_idempresa", emp_idempresa) :
                new ObjectParameter("emp_idempresa", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_APLICA_LOTE_SP", emp_idempresaParameter, idLoteParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_APLICA_LOTEDIRECTO_SP(Nullable<int> emp_idempresa, Nullable<decimal> idLote, Nullable<decimal> idUsuario)
        {
            var emp_idempresaParameter = emp_idempresa.HasValue ?
                new ObjectParameter("emp_idempresa", emp_idempresa) :
                new ObjectParameter("emp_idempresa", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_APLICA_LOTEDIRECTO_SP", emp_idempresaParameter, idLoteParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_APROBACION_REGRESO_SP(Nullable<int> proc_id, Nullable<int> nodo, Nullable<int> emp_idempresa, Nullable<decimal> idLote)
        {
            var proc_idParameter = proc_id.HasValue ?
                new ObjectParameter("proc_id", proc_id) :
                new ObjectParameter("proc_id", typeof(int));
    
            var nodoParameter = nodo.HasValue ?
                new ObjectParameter("nodo", nodo) :
                new ObjectParameter("nodo", typeof(int));
    
            var emp_idempresaParameter = emp_idempresa.HasValue ?
                new ObjectParameter("emp_idempresa", emp_idempresa) :
                new ObjectParameter("emp_idempresa", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_APROBACION_REGRESO_SP", proc_idParameter, nodoParameter, emp_idempresaParameter, idLoteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_APROBACION_SP(Nullable<int> proc_id, Nullable<int> nodo, Nullable<int> emp_idempresa, Nullable<decimal> idLote)
        {
            var proc_idParameter = proc_id.HasValue ?
                new ObjectParameter("proc_id", proc_id) :
                new ObjectParameter("proc_id", typeof(int));
    
            var nodoParameter = nodo.HasValue ?
                new ObjectParameter("nodo", nodo) :
                new ObjectParameter("nodo", typeof(int));
    
            var emp_idempresaParameter = emp_idempresa.HasValue ?
                new ObjectParameter("emp_idempresa", emp_idempresa) :
                new ObjectParameter("emp_idempresa", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_APROBACION_SP", proc_idParameter, nodoParameter, emp_idempresaParameter, idLoteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_APRUEBA_LOTE_SP(Nullable<int> proc_id, Nullable<int> nodo, Nullable<int> emp_idempresa, Nullable<decimal> idLote, Nullable<decimal> idUsuario, Nullable<decimal> idAprobador, string observacion, Nullable<decimal> idAprobacion, Nullable<decimal> not_identificador)
        {
            var proc_idParameter = proc_id.HasValue ?
                new ObjectParameter("proc_id", proc_id) :
                new ObjectParameter("proc_id", typeof(int));
    
            var nodoParameter = nodo.HasValue ?
                new ObjectParameter("nodo", nodo) :
                new ObjectParameter("nodo", typeof(int));
    
            var emp_idempresaParameter = emp_idempresa.HasValue ?
                new ObjectParameter("emp_idempresa", emp_idempresa) :
                new ObjectParameter("emp_idempresa", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var idAprobadorParameter = idAprobador.HasValue ?
                new ObjectParameter("idAprobador", idAprobador) :
                new ObjectParameter("idAprobador", typeof(decimal));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var idAprobacionParameter = idAprobacion.HasValue ?
                new ObjectParameter("idAprobacion", idAprobacion) :
                new ObjectParameter("idAprobacion", typeof(decimal));
    
            var not_identificadorParameter = not_identificador.HasValue ?
                new ObjectParameter("not_identificador", not_identificador) :
                new ObjectParameter("not_identificador", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_APRUEBA_LOTE_SP", proc_idParameter, nodoParameter, emp_idempresaParameter, idLoteParameter, idUsuarioParameter, idAprobadorParameter, observacionParameter, idAprobacionParameter, not_identificadorParameter);
        }
    
        public virtual ObjectResult<INS_DE_BPRO_A_PAGOS_SP_Result> INS_DE_BPRO_A_PAGOS_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INS_DE_BPRO_A_PAGOS_SP_Result>("INS_DE_BPRO_A_PAGOS_SP", idEmpresaParameter);
        }
    
        public virtual int INS_ERROR_SP(string componente, string mensaje)
        {
            var componenteParameter = componente != null ?
                new ObjectParameter("componente", componente) :
                new ObjectParameter("componente", typeof(string));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("mensaje", mensaje) :
                new ObjectParameter("mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_ERROR_SP", componenteParameter, mensajeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_LOTE_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idUsuario, string nombreLote, Nullable<short> estatus)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var nombreLoteParameter = nombreLote != null ?
                new ObjectParameter("nombreLote", nombreLote) :
                new ObjectParameter("nombreLote", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_LOTE_SP", idEmpresaParameter, idUsuarioParameter, nombreLoteParameter, estatusParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> INS_PAG_PROG_PAGOS_SP(Nullable<int> idEmpresa, Nullable<int> idUsuario, string nombreLote, Nullable<short> estatus, Nullable<short> esApliacionDirecta, Nullable<decimal> cifraControl)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var nombreLoteParameter = nombreLote != null ?
                new ObjectParameter("nombreLote", nombreLote) :
                new ObjectParameter("nombreLote", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(short));
    
            var esApliacionDirectaParameter = esApliacionDirecta.HasValue ?
                new ObjectParameter("esApliacionDirecta", esApliacionDirecta) :
                new ObjectParameter("esApliacionDirecta", typeof(short));
    
            var cifraControlParameter = cifraControl.HasValue ?
                new ObjectParameter("cifraControl", cifraControl) :
                new ObjectParameter("cifraControl", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INS_PAG_PROG_PAGOS_SP", idEmpresaParameter, idUsuarioParameter, nombreLoteParameter, estatusParameter, esApliacionDirectaParameter, cifraControlParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_PROG_PAGOS_SP(Nullable<decimal> idUsuario, Nullable<decimal> idPadre, string datosIngreso, string datosTransferencias, string datosTotales, Nullable<decimal> caja, Nullable<decimal> cobranzaEsperada, Nullable<int> operacion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            var datosIngresoParameter = datosIngreso != null ?
                new ObjectParameter("datosIngreso", datosIngreso) :
                new ObjectParameter("datosIngreso", typeof(string));
    
            var datosTransferenciasParameter = datosTransferencias != null ?
                new ObjectParameter("datosTransferencias", datosTransferencias) :
                new ObjectParameter("datosTransferencias", typeof(string));
    
            var datosTotalesParameter = datosTotales != null ?
                new ObjectParameter("datosTotales", datosTotales) :
                new ObjectParameter("datosTotales", typeof(string));
    
            var cajaParameter = caja.HasValue ?
                new ObjectParameter("caja", caja) :
                new ObjectParameter("caja", typeof(decimal));
    
            var cobranzaEsperadaParameter = cobranzaEsperada.HasValue ?
                new ObjectParameter("cobranzaEsperada", cobranzaEsperada) :
                new ObjectParameter("cobranzaEsperada", typeof(decimal));
    
            var operacionParameter = operacion.HasValue ?
                new ObjectParameter("operacion", operacion) :
                new ObjectParameter("operacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_PROG_PAGOS_SP", idUsuarioParameter, idPadreParameter, datosIngresoParameter, datosTransferenciasParameter, datosTotalesParameter, cajaParameter, cobranzaEsperadaParameter, operacionParameter);
        }
    
        public virtual ObjectResult<INS_PROV_BPRO_SP_Result> INS_PROV_BPRO_SP(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INS_PROV_BPRO_SP_Result>("INS_PROV_BPRO_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_PROVEEDOR_CUENTA_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idProveedor, string nombreProveedor, string cuentaPagadora)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("idProveedor", idProveedor) :
                new ObjectParameter("idProveedor", typeof(decimal));
    
            var nombreProveedorParameter = nombreProveedor != null ?
                new ObjectParameter("nombreProveedor", nombreProveedor) :
                new ObjectParameter("nombreProveedor", typeof(string));
    
            var cuentaPagadoraParameter = cuentaPagadora != null ?
                new ObjectParameter("cuentaPagadora", cuentaPagadora) :
                new ObjectParameter("cuentaPagadora", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_PROVEEDOR_CUENTA_SP", idEmpresaParameter, idProveedorParameter, nombreProveedorParameter, cuentaPagadoraParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_REF_AUTOMATICA_LOTE_DETALLE_SP(Nullable<decimal> idLote, Nullable<decimal> idProveedorPRM, Nullable<decimal> idReferencia, Nullable<int> numagrupamiento)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            var idProveedorPRMParameter = idProveedorPRM.HasValue ?
                new ObjectParameter("idProveedorPRM", idProveedorPRM) :
                new ObjectParameter("idProveedorPRM", typeof(decimal));
    
            var idReferenciaParameter = idReferencia.HasValue ?
                new ObjectParameter("idReferencia", idReferencia) :
                new ObjectParameter("idReferencia", typeof(decimal));
    
            var numagrupamientoParameter = numagrupamiento.HasValue ?
                new ObjectParameter("numagrupamiento", numagrupamiento) :
                new ObjectParameter("numagrupamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_REF_AUTOMATICA_LOTE_DETALLE_SP", idLoteParameter, idProveedorPRMParameter, idReferenciaParameter, numagrupamientoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_REF_AUTOMATICA_LOTE_SP(Nullable<decimal> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_REF_AUTOMATICA_LOTE_SP", idLoteParameter);
        }
    
        public virtual ObjectResult<string> PREPARA_PRUEBAS_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PREPARA_PRUEBAS_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<PROC_ACTUALIZA_CARTERA_SP_Result> PROC_ACTUALIZA_CARTERA_SP(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_ACTUALIZA_CARTERA_SP_Result>("PROC_ACTUALIZA_CARTERA_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<string> PROC_BORRA_LOTES_NO_APROBADOS_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_BORRA_LOTES_NO_APROBADOS_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_AGRUPADORES_PROVEEDOR_SP_Result> SEL_AGRUPADORES_PROVEEDOR_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_AGRUPADORES_PROVEEDOR_SP_Result>("SEL_AGRUPADORES_PROVEEDOR_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_AGRUPADORES_SP_Result> SEL_AGRUPADORES_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_AGRUPADORES_SP_Result>("SEL_AGRUPADORES_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_BUSCA_SERVIDOR_SP_Result> SEL_BUSCA_SERVIDOR_SP(string emp_nombre)
        {
            var emp_nombreParameter = emp_nombre != null ?
                new ObjectParameter("emp_nombre", emp_nombre) :
                new ObjectParameter("emp_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_BUSCA_SERVIDOR_SP_Result>("SEL_BUSCA_SERVIDOR_SP", emp_nombreParameter);
        }
    
        public virtual ObjectResult<SEL_CUENTAS_EGRESOS_SP_Result> SEL_CUENTAS_EGRESOS_SP(Nullable<decimal> idEmpresa, Nullable<decimal> numLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var numLoteParameter = numLote.HasValue ?
                new ObjectParameter("numLote", numLote) :
                new ObjectParameter("numLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_CUENTAS_EGRESOS_SP_Result>("SEL_CUENTAS_EGRESOS_SP", idEmpresaParameter, numLoteParameter);
        }
    
        public virtual ObjectResult<SEL_CUENTAS_EGRESOS_SPBK_Result> SEL_CUENTAS_EGRESOS_SPBK(Nullable<decimal> idEmpresa, Nullable<decimal> numLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var numLoteParameter = numLote.HasValue ?
                new ObjectParameter("numLote", numLote) :
                new ObjectParameter("numLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_CUENTAS_EGRESOS_SPBK_Result>("SEL_CUENTAS_EGRESOS_SPBK", idEmpresaParameter, numLoteParameter);
        }
    
        public virtual ObjectResult<SEL_CUENTAS_INGRESOS_SP_Result> SEL_CUENTAS_INGRESOS_SP(Nullable<decimal> idEmpresa, Nullable<decimal> numLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var numLoteParameter = numLote.HasValue ?
                new ObjectParameter("numLote", numLote) :
                new ObjectParameter("numLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_CUENTAS_INGRESOS_SP_Result>("SEL_CUENTAS_INGRESOS_SP", idEmpresaParameter, numLoteParameter);
        }
    
        public virtual ObjectResult<SEL_CUENTAS_TRANSFERENCIAS_SP_Result> SEL_CUENTAS_TRANSFERENCIAS_SP(Nullable<decimal> idLotePago)
        {
            var idLotePagoParameter = idLotePago.HasValue ?
                new ObjectParameter("idLotePago", idLotePago) :
                new ObjectParameter("idLotePago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_CUENTAS_TRANSFERENCIAS_SP_Result>("SEL_CUENTAS_TRANSFERENCIAS_SP", idLotePagoParameter);
        }
    
        public virtual ObjectResult<string> SEL_ELIMINA_LOTE_SP_Borrar(Nullable<decimal> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_ELIMINA_LOTE_SP_Borrar", idLoteParameter);
        }
    
        public virtual ObjectResult<SEL_EMPLEADO_SP_Result> SEL_EMPLEADO_SP(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_EMPLEADO_SP_Result>("SEL_EMPLEADO_SP", idEmpleadoParameter);
        }
    
        public virtual ObjectResult<SEL_EMPRESAS_SP_Result> SEL_EMPRESAS_SP(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_EMPRESAS_SP_Result>("SEL_EMPRESAS_SP", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_EMPRESAS_SP_BK_Result> SEL_EMPRESAS_SP_BK(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_EMPRESAS_SP_BK_Result>("SEL_EMPRESAS_SP_BK", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_EMPRESAS_SP4_Result> SEL_EMPRESAS_SP4(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_EMPRESAS_SP4_Result>("SEL_EMPRESAS_SP4", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_ENCABEZADO_SP_Result> SEL_ENCABEZADO_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ENCABEZADO_SP_Result>("SEL_ENCABEZADO_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_ESCENARIO_SP_Result> SEL_ESCENARIO_SP(Nullable<int> idEscenario)
        {
            var idEscenarioParameter = idEscenario.HasValue ?
                new ObjectParameter("idEscenario", idEscenario) :
                new ObjectParameter("idEscenario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ESCENARIO_SP_Result>("SEL_ESCENARIO_SP", idEscenarioParameter);
        }
    
        public virtual ObjectResult<SEL_INGRESO_OTROS_SP_Result> SEL_INGRESO_OTROS_SP(Nullable<decimal> idLotePago)
        {
            var idLotePagoParameter = idLotePago.HasValue ?
                new ObjectParameter("idLotePago", idLotePago) :
                new ObjectParameter("idLotePago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_INGRESO_OTROS_SP_Result>("SEL_INGRESO_OTROS_SP", idLotePagoParameter);
        }
    
        public virtual ObjectResult<SEL_LOTE_DETALLE_COMPLETO_SP_Result> SEL_LOTE_DETALLE_COMPLETO_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOTE_DETALLE_COMPLETO_SP_Result>("SEL_LOTE_DETALLE_COMPLETO_SP", idEmpresaParameter, idLoteParameter);
        }
    
        public virtual ObjectResult<SEL_LOTE_DETALLE_SP_Result> SEL_LOTE_DETALLE_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idUsuario, Nullable<decimal> idLotePago)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var idLotePagoParameter = idLotePago.HasValue ?
                new ObjectParameter("idLotePago", idLotePago) :
                new ObjectParameter("idLotePago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOTE_DETALLE_SP_Result>("SEL_LOTE_DETALLE_SP", idEmpresaParameter, idUsuarioParameter, idLotePagoParameter);
        }
    
        public virtual ObjectResult<SEL_LOTE_SP_Result> SEL_LOTE_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idUsuario, Nullable<int> borraLotes, Nullable<decimal> idLote)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var borraLotesParameter = borraLotes.HasValue ?
                new ObjectParameter("borraLotes", borraLotes) :
                new ObjectParameter("borraLotes", typeof(int));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOTE_SP_Result>("SEL_LOTE_SP", idEmpresaParameter, idUsuarioParameter, borraLotesParameter, idLoteParameter);
        }
    
        public virtual ObjectResult<SEL_LOTESXFECHA_SP_Result> SEL_LOTESXFECHA_SP(Nullable<decimal> idEmpresa, Nullable<decimal> idUsuario, string fecha_ini, string fecha_fin, Nullable<int> estatus)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("estatus", estatus) :
                new ObjectParameter("estatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOTESXFECHA_SP_Result>("SEL_LOTESXFECHA_SP", idEmpresaParameter, idUsuarioParameter, fecha_iniParameter, fecha_finParameter, estatusParameter);
        }
    
        public virtual ObjectResult<SEL_PROG_PAGOS_GUARDADA_SP_Result> SEL_PROG_PAGOS_GUARDADA_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROG_PAGOS_GUARDADA_SP_Result>("SEL_PROG_PAGOS_GUARDADA_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<SEL_PROG_PAGOS_TXT_SP_Result> SEL_PROG_PAGOS_TXT_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROG_PAGOS_TXT_SP_Result>("SEL_PROG_PAGOS_TXT_SP", idPadreParameter);
        }
    
        public virtual int SEL_PROG_PAGOS_TXT_SP_BK(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEL_PROG_PAGOS_TXT_SP_BK", idPadreParameter);
        }
    
        public virtual ObjectResult<string> SEL_PROG_PAGOS_TXTGRP_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_PROG_PAGOS_TXTGRP_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<SEL_PROGRAMACION_PAGOS_SP_Result> SEL_PROGRAMACION_PAGOS_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROGRAMACION_PAGOS_SP_Result>("SEL_PROGRAMACION_PAGOS_SP", idEmpresaParameter);
        }
    
        public virtual int SEL_PROGRAMACION_PAGOS_SP_QueryBPRO(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEL_PROGRAMACION_PAGOS_SP_QueryBPRO", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_PROGRAMACION_PAGOSXVENCER_SP_Result> SEL_PROGRAMACION_PAGOSXVENCER_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROGRAMACION_PAGOSXVENCER_SP_Result>("SEL_PROGRAMACION_PAGOSXVENCER_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_PROVEEDORES_CTA_PAGADORA_SP_Result> SEL_PROVEEDORES_CTA_PAGADORA_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROVEEDORES_CTA_PAGADORA_SP_Result>("SEL_PROVEEDORES_CTA_PAGADORA_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_PROVEEDORES_SP_Result> SEL_PROVEEDORES_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROVEEDORES_SP_Result>("SEL_PROVEEDORES_SP", idEmpresaParameter);
        }
    
        public virtual int SEL_TIPO_CON_CONFCONTA(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEL_TIPO_CON_CONFCONTA", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_TOTAL_BANCOS_LOTE_SP_Result> SEL_TOTAL_BANCOS_LOTE_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TOTAL_BANCOS_LOTE_SP_Result>("SEL_TOTAL_BANCOS_LOTE_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<SEL_TOTAL_BANCOS_P_NP_SP_Result> SEL_TOTAL_BANCOS_P_NP_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TOTAL_BANCOS_P_NP_SP_Result>("SEL_TOTAL_BANCOS_P_NP_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_TOTAL_BANCOS_SP_Result> SEL_TOTAL_BANCOS_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TOTAL_BANCOS_SP_Result>("SEL_TOTAL_BANCOS_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_LIBERAR_CXP_SP_Result> SEL_LIBERAR_CXP_SP(Nullable<int> idlote)
        {
            var idloteParameter = idlote.HasValue ?
                new ObjectParameter("idlote", idlote) :
                new ObjectParameter("idlote", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LIBERAR_CXP_SP_Result>("SEL_LIBERAR_CXP_SP", idloteParameter);
        }
    
        public virtual ObjectResult<SEL_TRANSFERENCIASXEMPRESA_Result> SEL_TRANSFERENCIASXEMPRESA(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TRANSFERENCIASXEMPRESA_Result>("SEL_TRANSFERENCIASXEMPRESA", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_TRANSFERENCIASXEMPRESAXFECHA_Result> SEL_TRANSFERENCIASXEMPRESAXFECHA(Nullable<int> idEmpresa, string fecha_ini, string fecha_fin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TRANSFERENCIASXEMPRESAXFECHA_Result>("SEL_TRANSFERENCIASXEMPRESAXFECHA", idEmpresaParameter, fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<SEL_TRANSFERENCIASXLOTE_Result> SEL_TRANSFERENCIASXLOTE(Nullable<int> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TRANSFERENCIASXLOTE_Result>("SEL_TRANSFERENCIASXLOTE", idLoteParameter);
        }
    
        public virtual ObjectResult<SEL_USUARIO_TRANSFERENCIA_Result> SEL_USUARIO_TRANSFERENCIA(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_USUARIO_TRANSFERENCIA_Result>("SEL_USUARIO_TRANSFERENCIA", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SEL_USUARIOS_SP_Result> SEL_USUARIOS_SP(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_USUARIOS_SP_Result>("SEL_USUARIOS_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<string> UPD_TRANSFERENCIASXEMPRESA(Nullable<int> idLote, Nullable<decimal> importe)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("idLote", idLote) :
                new ObjectParameter("idLote", typeof(int));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("importe", importe) :
                new ObjectParameter("importe", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_TRANSFERENCIASXEMPRESA", idLoteParameter, importeParameter);
        }
    
        public virtual ObjectResult<SEL_PROGRAMACION_PAGOSENROJO_SP_Result> SEL_PROGRAMACION_PAGOSENROJO_SP(Nullable<decimal> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PROGRAMACION_PAGOSENROJO_SP_Result>("SEL_PROGRAMACION_PAGOSENROJO_SP", idEmpresaParameter);
        }
    
        public virtual ObjectResult<SEL_ERRORES_CXP_SP_Result> SEL_ERRORES_CXP_SP(Nullable<int> idlote)
        {
            var idloteParameter = idlote.HasValue ?
                new ObjectParameter("idlote", idlote) :
                new ObjectParameter("idlote", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_ERRORES_CXP_SP_Result>("SEL_ERRORES_CXP_SP", idloteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> INS_PROG_PAGOS_AUTORIZA_SP(Nullable<decimal> idUsuario, Nullable<decimal> idPadre)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(decimal));
    
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("INS_PROG_PAGOS_AUTORIZA_SP", idUsuarioParameter, idPadreParameter);
        }
    
        public virtual ObjectResult<string> SEL_PROG_PAGOS_BANAMEX_TXT_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_PROG_PAGOS_BANAMEX_TXT_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<string> SEL_PROG_FIND_BANK_TXT_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_PROG_FIND_BANK_TXT_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<string> SEL_PROG_FIND_NAMELOTE_SP(Nullable<decimal> idPadre)
        {
            var idPadreParameter = idPadre.HasValue ?
                new ObjectParameter("idPadre", idPadre) :
                new ObjectParameter("idPadre", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_PROG_FIND_NAMELOTE_SP", idPadreParameter);
        }
    
        public virtual ObjectResult<string> INS_BITACORA_POGRA_PAGOS_DET(string numeroTransaccion, Nullable<int> idLotePago)
        {
            var numeroTransaccionParameter = numeroTransaccion != null ?
                new ObjectParameter("NumeroTransaccion", numeroTransaccion) :
                new ObjectParameter("NumeroTransaccion", typeof(string));
    
            var idLotePagoParameter = idLotePago.HasValue ?
                new ObjectParameter("idLotePago", idLotePago) :
                new ObjectParameter("idLotePago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INS_BITACORA_POGRA_PAGOS_DET", numeroTransaccionParameter, idLotePagoParameter);
        }
    
        public virtual ObjectResult<SEL_RUTA_CONFIGURACION_Result> SEL_RUTA_CONFIGURACION(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_RUTA_CONFIGURACION_Result>("SEL_RUTA_CONFIGURACION", idParameter);
        }
    
        public virtual ObjectResult<SEL_PAGOS_DETALLES_BITACORA_Result> SEL_PAGOS_DETALLES_BITACORA(string numeroTransaccion, Nullable<int> idLotePago, Nullable<int> estatusTransaccion)
        {
            var numeroTransaccionParameter = numeroTransaccion != null ?
                new ObjectParameter("NumeroTransaccion", numeroTransaccion) :
                new ObjectParameter("NumeroTransaccion", typeof(string));
    
            var idLotePagoParameter = idLotePago.HasValue ?
                new ObjectParameter("idLotePago", idLotePago) :
                new ObjectParameter("idLotePago", typeof(int));
    
            var estatusTransaccionParameter = estatusTransaccion.HasValue ?
                new ObjectParameter("estatusTransaccion", estatusTransaccion) :
                new ObjectParameter("estatusTransaccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_PAGOS_DETALLES_BITACORA_Result>("SEL_PAGOS_DETALLES_BITACORA", numeroTransaccionParameter, idLotePagoParameter, estatusTransaccionParameter);
        }
    
        public virtual ObjectResult<SEL_FORMATO_SFTP_Result> SEL_FORMATO_SFTP(Nullable<int> iDBanco)
        {
            var iDBancoParameter = iDBanco.HasValue ?
                new ObjectParameter("IDBanco", iDBanco) :
                new ObjectParameter("IDBanco", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_FORMATO_SFTP_Result>("SEL_FORMATO_SFTP", iDBancoParameter);
        }
    }
}
